name: Fetch Data and Create PR
on:
  repository_dispatch:
    types:
      - webhook
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Event Type from Payload
        id: extract_event
        run: echo "${{ github.event.client_payload}}"

